'use client';
import { useState } from 'react';
import { AtlasData, DEFAULT, Filters, STATUS } from '@/lib/atlas';
import { Sheet } from './AtlasShared';
export function YearStatusControls({filters,update}: {filters:Filters;update:(p:Partial<Filters>)=>void}) {return <><label>Estado al corte<select value={filters.status} onChange={e=>update({status:e.target.value,page:1})}>{STATUS.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></label><label>Presentado desde<input type="number" min={1993} max={filters.to} value={filters.from} onChange={e=>update({from:Math.min(filters.to,Math.max(1993,Number(e.target.value)||1993)),page:1})}/></label><label>Hasta<input type="number" min={filters.from} max={2026} value={filters.to} onChange={e=>update({to:Math.max(filters.from,Math.min(2026,Number(e.target.value)||2026)),page:1})}/></label></>;}
export default function AtlasControls({data,filters,update}: {data:AtlasData;filters:Filters;update:(p:Partial<Filters>)=>void}) {
 const [open,setOpen]=useState(false);
 const fields=<div className="atlas-fields">{(['region','sector','titular'] as const).map((dim,i)=><label key={dim}>{['Región','Sector','Empresa'][i]}<select value={filters[dim]} onChange={e=>update({[dim]:e.target.value,page:1})}><option value="">{['Todas las regiones','Todos los sectores','Todas las empresas'][i]}</option>{data.entities[dim].map(e=><option value={e.key} key={e.key}>{e.name}</option>)}</select></label>)}<YearStatusControls filters={filters} update={update}/></div>;
 const active=Object.entries(filters).filter(([k,v])=>['region','sector','titular','q'].includes(k)&&v);
 return <div className="atlas-controls"><div className="atlas-search-row"><label className="atlas-search"><span className="sr-only">Buscar proyectos o empresas</span><span aria-hidden="true">⌕</span><input type="search" placeholder="Busca un proyecto, empresa o territorio" value={filters.q} onChange={e=>update({q:e.target.value,page:1})}/></label><button className="atlas-button mobile-filter" onClick={()=>setOpen(true)}>Filtros ({active.length})</button><button className="atlas-button" onClick={()=>update({...DEFAULT})}>Restablecer</button></div><div className="desktop-filters">{fields}</div>{open&&<Sheet title="Filtrar el atlas" close={()=>setOpen(false)}>{fields}<button className="atlas-button primary" onClick={()=>setOpen(false)}>Ver resultados</button></Sheet>}<div className="filter-chips" aria-label="Filtros activos"><span>{STATUS.find(s=>s.key===filters.status)?.label} · {filters.from}–{filters.to}</span>{active.map(([k,v])=><button key={k} onClick={()=>update({[k]:'',page:1})}>{k==='q'?v:data.entities[k as 'region'].find(e=>e.key===v)?.name || v} <span aria-label="Quitar filtro">×</span></button>)}</div></div>;
}
