'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import Header from './Header';import Footer from './Footer';import AtlasMap from './AtlasMap';import AtlasControls from './AtlasControls';import ProjectDetail from './ProjectDetail';
import { CutoffNote, DataState, MetricSummary } from './AtlasShared';
import { atlasHref, filterProjects, money, paramsFor } from '@/lib/atlas';
import { useAtlas, useFilters } from '@/lib/useAtlas';
export default function AtlasWorkspace({view}: {view:'mapa'|'explorador'}) {
 const {data,error,retry}=useAtlas(),{filters,update}=useFilters();const [copied,setCopied]=useState('');
 const rows=useMemo(()=>{const list=data?filterProjects(data.projects,filters):[];return list.sort((a,b)=>filters.sort==='recent'?b.fp.localeCompare(a.fp):filters.sort==='name'?a.n.localeCompare(b.n,'es'):b.m-a.m || a.id-b.id);},[data,filters]);
 const pages=Math.max(1,Math.ceil(rows.length/25)),page=Math.min(filters.page,pages),visible=rows.slice((page-1)*25,page*25);
 const copy=async()=>{try{await navigator.clipboard.writeText(window.location.href);setCopied('Enlace copiado');}catch{setCopied('Copia la dirección de tu navegador');}};
 const compareParams=paramsFor({...filters,project:null,page:1});compareParams.set('type','region');if(filters.region)compareParams.set('entities',filters.region);compareParams.delete('region');
 return <><Header/><main className="atlas-workspace page-shell"><div className="workspace-heading"><div><p className="oep-kicker">PROYECTOS DE INVERSIÓN</p><h1 className="oep-page-title">Mapa de proyectos</h1><p>Explora los expedientes por territorio, sector y empresa.</p></div><div className="workspace-actions"><Link className="atlas-button" href={`/comparar/?${compareParams}`}>Comparar regiones ↗</Link><button className="atlas-button" onClick={copy}>{copied||'Compartir enlace'}</button></div></div>{!data?<DataState error={error} retry={retry}/>:<><AtlasControls data={data} filters={filters} update={p=>update(p)}/><MetricSummary projects={rows}/><div className="view-toolbar"><div className="view-tabs" aria-label="Vista del atlas"><Link aria-current={view==='mapa'?'page':undefined} href={atlasHref(filters)}>◎ Mapa</Link><Link aria-current={view==='explorador'?'page':undefined} href={atlasHref(filters,'explorador')}>☷ Tabla</Link></div><label>Ordenar<select value={filters.sort} onChange={e=>update({sort:e.target.value,page:1})}><option value="investment">Mayor inversión</option><option value="recent">Más recientes</option><option value="name">Nombre A–Z</option></select></label></div>{rows.length===0?<div className="data-state"><h2>No hay expedientes con estos filtros.</h2><p>Amplía el período o quita un filtro para continuar.</p></div>:<div className={view==='mapa'?'workspace-map-grid':''}>{view==='mapa'&&<AtlasMap projects={rows} region={filters.region} onSelect={id=>update({project:id})}/>}<div className="project-results">{view==='mapa'?<><h2 className="oep-headline">Proyectos de la selección</h2><p className="atlas-note">Lista seleccionable, incluidos los expedientes sin coordenadas.</p>{visible.map(p=><button className="project-list-row" key={p.id} onClick={()=>update({project:p.id})}><span>{p.n}<small>{p.rg} · {p.e}</small></span><strong>{money(p.m)}<small>US$ MM</small></strong></button>)}</>:<div className="table-scroll"><table className="atlas-table"><caption className="sr-only">Expedientes filtrados, incluye proyectos sin coordenadas</caption><thead><tr><th>Proyecto / empresa</th><th>Región / sector</th><th>Estado al corte</th><th>Presentación</th><th>US$ MM</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><button onClick={()=>update({project:p.id})}>{p.n}</button><small>{p.ti}</small></td><td>{p.rg}<small>{p.s}{p.la==null?' · Sin coordenadas':''}</small></td><td>{p.e}</td><td>{p.fp}</td><td className="font-mono">{money(p.m)}</td></tr>)}</tbody></table></div>}<div className="pagination"><button className="atlas-button" disabled={page<=1} onClick={()=>update({page:page-1})}>← Anterior</button><span>Página {page} de {pages}</span><button className="atlas-button" disabled={page>=pages} onClick={()=>update({page:page+1})}>Siguiente →</button></div></div></div>}<CutoffNote/></>}{filters.project&&<ProjectDetail id={filters.project} close={()=>update({project:null})}/>}</main><Footer/></>;
}
