'use client';
import { useEffect, useMemo, useState } from 'react';
import { AtlasProject, continental, getJson, hasCoords, money, normalize, statusColor } from '@/lib/atlas';
import { ChartLegend, Sheet } from './AtlasShared';
export default function AtlasMap({projects,region='',onSelect,compact=false}: {projects:AtlasProject[];region?:string;onSelect:(id:number)=>void;compact?:boolean}) {
 const [outline,setOutline]=useState<any>(null),[error,setError]=useState(false),[zoom,setZoom]=useState(1),[cluster,setCluster]=useState<AtlasProject[]>([]),[query,setQuery]=useState('');
 const load=()=>{setError(false);getJson('geo/chile.json').then(setOutline).catch(()=>setError(true));};
 useEffect(load,[]); useEffect(()=>{setZoom(1);setCluster([]);},[region,projects]);
 const located=useMemo(()=>projects.filter(region?hasCoords:continental),[projects,region]);
 const projectXY=(lon:number,lat:number)=>[lon*.8,-lat];
 const bounds=useMemo(()=>{if(!region || !located.length)return [-61.2,17,8.4,39.5]; const x=located.map(p=>p.lo!*.8),y=located.map(p=>-p.la!);const minX=Math.min(...x),maxX=Math.max(...x),minY=Math.min(...y),maxY=Math.max(...y);const w=Math.max(2,maxX-minX),h=Math.max(3,maxY-minY);return[minX-.5,minY-.7,w+1,h+1.4];},[region,located]);
 const [bx,by,bw,bh]=bounds;
 const view=[bx+bw*(1-1/zoom)/2,by+bh*(1-1/zoom)/2,bw/zoom,bh/zoom];
 const grouped=useMemo(()=>{const map=new Map<string,AtlasProject[]>();for(const p of located){const key=`${Math.round(p.lo!*20)}:${Math.round(p.la!*20)}`;const group=map.get(key)||[];group.push(p);map.set(key,group);}return Array.from(map.values());},[located]);
 const paths=outline?.features.flatMap((f:any)=>f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates]).map((polygon:any)=>polygon.map((ring:number[][])=>ring.map(([lon,lat],i)=>`${i?'L':'M'}${projectXY(lon,lat).join(',')}`).join(' ')+'Z').join(' '));
 return <div className={`atlas-map ${compact?'compact':''}`}><div className="map-topline"><span className="map-caption">CHILE / {region?'SELECCIÓN REGIONAL':'VISTA CONTINENTAL'}</span><div className="map-tools"><button className="map-list-button" aria-label="Elegir proyecto de la lista del mapa" onClick={()=>{setQuery('');setCluster(projects);}}>☷</button><button aria-label="Acercar mapa" onClick={()=>setZoom(z=>Math.min(5,z*1.4))}>+</button><button aria-label="Alejar mapa" onClick={()=>setZoom(z=>Math.max(1,z/1.4))}>−</button><button aria-label="Restablecer mapa" onClick={()=>setZoom(1)}>↺</button></div></div>{error?<div role="alert">No se pudo cargar el contorno. <button onClick={load}>Reintentar</button></div>:<svg className="chile-atlas-svg" viewBox={view.join(' ')} role="img" aria-label={`Mapa de ${money(located.length)} proyectos. Selecciona un punto o usa la lista de proyectos.`}>
 <defs><pattern id="atlas-grid" width="2" height="2" patternUnits="userSpaceOnUse"><path d="M 2 0 L 0 0 0 2" fill="none" stroke="#ffffff" strokeOpacity=".09" strokeWidth=".025"/></pattern></defs><rect x={-150} y={-90} width={300} height={180} fill="url(#atlas-grid)"/>
 {paths?.map((d:string,i:number)=><path key={i} d={d} fill="#2d4050" stroke="#80929c" strokeWidth={.05} fillRule="evenodd"/>)}
 {grouped.map(group=>{const p=group[0];const total=group.reduce((a,p)=>a+p.m,0);const [x,y]=projectXY(p.lo!,p.la!);return <circle key={p.id} cx={x} cy={y} r={Math.min(.36,.075+Math.sqrt(total)/450)/Math.sqrt(zoom)} fill={group.every(x=>x.e===p.e)?statusColor(p):'#94a3b8'} fillOpacity={.85} stroke={group.every(x=>x.e===p.e)?statusColor(p):'#94a3b8'} strokeWidth={.025} onClick={()=>group.length>1?setCluster(group):onSelect(p.id)} style={{cursor:'pointer'}}><title>{group.length>1?`${group.length} proyectos superpuestos`:p.n} · US$ {money(total)} MM</title></circle>;})}</svg>}
 {!region&&<><span className="map-ocean">OCÉANO<br/>PACÍFICO</span><span className="map-north">N ↑</span></>}
 <div className="map-bottom"><ChartLegend/><p>{money(located.length)} visibles / {money(projects.length)} expedientes · {money(projects.length-projects.filter(hasCoords).length)} sin coordenadas{!region&&` · ${money(projects.filter(hasCoords).length-located.length)} fuera de vista continental`}</p></div>
 {cluster.length>0&&<Sheet title={`${money(cluster.length)} proyectos de la selección`} close={()=>setCluster([])}><label className="atlas-search mt-6"><span className="sr-only">Buscar en proyectos del mapa</span><input type="search" placeholder="Buscar en esta selección" value={query} onChange={e=>setQuery(e.target.value)}/></label><p className="atlas-note">Proyectos superpuestos y selección geográfica. Se muestran hasta 50 coincidencias; busca por nombre o empresa.</p>{cluster.filter(p=>normalize(`${p.n} ${p.ti}`).includes(normalize(query))).slice(0,50).map(p=><button className="project-list-row" key={p.id} onClick={()=>{setCluster([]);onSelect(p.id);}}><span>{p.n}<small>{p.e}</small></span><strong>{money(p.m)}<small>US$ MM</small></strong></button>)}</Sheet>}
 </div>;
}
