'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';
import Footer from '@/components/Footer';import ComparisonSelection from '@/components/ComparisonSelection';import {YearStatusControls} from '@/components/AtlasControls';import {CutoffNote,DataState} from '@/components/AtlasShared';
import {atlasHref,DEFAULT,Dimension,dimensionKey,filterProjects,Filters,metrics,money,paramsFor,readFilters} from '@/lib/atlas';import {useAtlas} from '@/lib/useAtlas';
export default function ComparisonWorkspace(){const {data,error,retry}=useAtlas();const [type,setType]=useState<Dimension>('region'),[keys,setKeys]=useState<string[]>([]),[f,setF]=useState<Filters>({...DEFAULT,status:'all'}),[copied,setCopied]=useState('');
useEffect(()=>{const restore=()=>{const p=new URLSearchParams(window.location.search);setType(['region','sector','titular'].includes(p.get('type')!)?p.get('type') as Dimension:'region');setKeys(Array.from(new Set((p.get('entities')||'').split(','))).slice(0,3));setF(readFilters(p,{...DEFAULT,status:'all'}));};restore();window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[]);
const save=(nextType=type,nextKeys=keys,nextF=f)=>{setType(nextType);setKeys(nextKeys);setF(nextF);const p=paramsFor({...nextF,project:null,page:1});p.set('type',nextType);p.set('entities',nextKeys.join(','));p.delete(nextType);window.history.pushState(null,'',`${window.location.pathname}?${p}`);};
const scoped={...f,[type]:'',project:null};const base=data?filterProjects(data.projects,scoped):[];
const selected=keys.filter(Boolean).map(key=>{const entity=data?.entities[type].find(e=>e.key===key);const projects=base.filter(p=>p[dimensionKey[type]]===key);return {key,entity,projects,m:metrics(projects)};});const max=Math.max(...selected.map(s=>s.m.investment),1);
const percent=(n:number|null)=>n==null?'No disponible':`${(100*n).toLocaleString('es-CL',{maximumFractionDigits:1})} %`;
return <><main className="page-shell"><div className="workspace-heading"><div><p className="oep-kicker">COMPARAR / MISMA BASE, DISTINTAS CARTERAS</p><h1 className="oep-page-title">Pon la inversión en perspectiva.</h1><p>Hasta tres regiones, sectores o empresas, con un mismo período.</p></div><Link className="atlas-button" href="/rankings/">Ver rankings ↗</Link></div>{!data?<DataState error={error} retry={retry}/>:<><div className="comparison-controls"><label>Qué comparar<select value={type} onChange={e=>save(e.target.value as Dimension,[],f)}><option value="region">Regiones</option><option value="sector">Sectores</option><option value="titular">Empresas</option></select></label><YearStatusControls filters={f} update={p=>save(type,keys,{...f,...p})}/></div><ComparisonSelection data={data} type={type} keys={keys} change={next=>save(type,next)}/><div className="comparison-scope">Alcance: presentación {f.from}–{f.to}. La selección reemplaza el filtro de {type==='region'?'región':type==='sector'?'sector':'empresa'}; conserva año, estado y los demás filtros del atlas.{(['region','sector','titular'] as const).filter(d=>d!==type&&f[d]).map(d=><span key={d}> · {data.entities[d].find(e=>e.key===f[d])?.name||f[d]}</span>)}{f.q&&<span> · Búsqueda: {f.q}</span>} Incluye expedientes sin coordenadas.</div><button className="atlas-button" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);setCopied('Enlace copiado');}catch{setCopied('Copia la dirección de tu navegador');}}}>{copied||'Compartir comparación'}</button>{selected.length?<div className="compare-grid">{selected.map(({key,entity,m})=><section className="compare-card" key={key}><h2>{entity?.name||'Entidad no disponible'}</h2><div className="compare-bar"><i style={{width:`${m.investment/max*100}%`}}/></div><dl><div><dt>Inversión declarada · US$ MM</dt><dd>{money(m.investment)}</dd><small>Suma antes del redondeo</small></div><div><dt>Expedientes</dt><dd>{money(m.count)}</dd><small>{money(m.mapped)} con coordenadas</small></div><div><dt>Tasa de calificación</dt><dd>{percent(m.qualificationRate)}</dd><small>{money(m.qualified)} con RCA / {money(m.count)} expedientes</small></div><div><dt>Tasa de aprobación</dt><dd>{percent(m.approvalRate)}</dd><small>{money(m.approved)} aprobados / {money(m.qualified)} calificados</small></div><div><dt>Mediana de tramitación</dt><dd>{m.median==null?'No disponible':`${money(m.median)} días`}</dd><small>{money(m.durationN)} expedientes con ambas fechas</small></div></dl>{!m.count&&<p className="atlas-note">Sin expedientes para este alcance.</p>}<Link href={atlasHref({...f,[type]:key,project:null,page:1})}>Explorar cartera ↗</Link>{entity?.profile&&<Link href={`/perfiles/${type}-${key}/?${paramsFor({...f,[type]:key})}`}>Ver perfil ↗</Link>}</section>)}</div>:<div className="data-state"><h2>Elige la primera entidad para comenzar.</h2><p>Agrega una segunda para leer ambas carteras lado a lado.</p></div>}<CutoffNote/></>}</main><Footer/></>;
}
