'use client';
import Link from 'next/link';import dynamic from 'next/dynamic';import {useMemo} from 'react';
import type {Profile} from '@/lib/profile';import {atlasHref,breakdown,DEFAULT,filterProjects,metrics,money,paramsFor} from '@/lib/atlas';import {useAtlas,useFilters} from '@/lib/useAtlas';
import {YearStatusControls} from './AtlasControls';import {CutoffNote,DataState,MetricSummary} from './AtlasShared';import ProjectDetail from './ProjectDetail';
const ProfileChart=dynamic(()=>import('./ProfileChart'),{ssr:false});
export default function ProfileView({p}:{p:Pick<Profile,'tipo'|'slug'|'nombre'|'rank'>}) {
 const {data,error,retry}=useAtlas(),{filters,update}=useFilters({...DEFAULT,status:'all'});
 const scoped={...filters,[p.tipo]:p.slug};const projects=useMemo(()=>data?filterProjects(data.projects,scoped):[],[data,filters,p]);const m=metrics(projects);
 const dimension=p.tipo==='region'?'sector':'region';const parts=breakdown(projects,dimension);const companies=breakdown(projects,'titular').slice(0,8);
 const recent=[...projects].sort((a,b)=>b.fp.localeCompare(a.fp)).slice(0,12);
 const annual=Array.from({length:filters.to-filters.from+1},(_,i)=>{const year=filters.from+i;const list=projects.filter(p=>p.a===year);return{anio:year,proyectos:list.length,inversion_mmu:metrics(list).investment,aprobados_n:list.filter(p=>p.e==='Aprobado').length};});
 const compare=paramsFor({...scoped,project:null});compare.delete(p.tipo);compare.set('type',p.tipo);compare.set('entities',p.slug);
 const entityLink=(dim:'region'|'sector'|'titular',key:string)=>{const e=data?.entities[dim].find(e=>e.key===key);const f={...scoped,[dim]:key,project:null,page:1};return e?.profile?`/perfiles/${dim}-${key}/?${paramsFor(f)}`:atlasHref(f);};
 return <main className="page-shell"><Link className="atlas-note" href="/perfiles/">Actores y territorio / {p.tipo==='region'?'Región':p.tipo==='sector'?'Sector':'Empresa'}</Link><div className="workspace-heading"><div><h1 className="oep-page-title">{p.nombre}</h1><p>La cartera, sus actores y sus tiempos de evaluación.</p></div><div className="workspace-actions"><Link className="atlas-button" href={atlasHref(scoped)}>Explorar cartera ↗</Link><Link className="atlas-button" href={`/comparar/?${compare}`}>Comparar ↗</Link></div></div>{!data?<DataState error={error} retry={retry}/>:<><div className="comparison-controls"><YearStatusControls filters={filters} update={p=>update(p)}/></div>{(['region','sector','titular'] as const).filter(d=>d!==p.tipo&&filters[d]).map(d=><p className="atlas-note" key={d}>Filtro adicional: {data.entities[d].find(e=>e.key===filters[d])?.name||filters[d]} <button onClick={()=>update({[d]:''})}>Quitar ×</button></p>)}{filters.q&&<p className="atlas-note">Búsqueda: {filters.q} <button onClick={()=>update({q:''})}>Quitar ×</button></p>}<MetricSummary projects={projects}/><p className="atlas-note">Aprobación: {m.approvalRate==null?'No disponible':`${(m.approvalRate*100).toLocaleString('es-CL',{maximumFractionDigits:1})} %`} · {money(m.approved)} aprobados / {money(m.qualified)} calificados con RCA. Incluye {money(m.count-m.mapped)} expedientes sin coordenadas.</p>{!projects.length?<div className="data-state">No hay expedientes en este período y estado.</div>:<div className="profile-grid"><div><h2 className="oep-headline text-2xl mt-10">Inversión por año de presentación</h2><ProfileChart serie={annual}/><h2 className="oep-headline text-2xl mt-10">{dimension==='sector'?'Composición sectorial':'Distribución regional'}</h2>{parts.map(r=><Link className="project-list-row" key={r.key} href={entityLink(dimension,r.key)}><span>{r.name}<small>{money(r.count)} expedientes</small></span><strong>{money(r.investment)}<small>US$ MM</small></strong></Link>)}{p.tipo!=='titular'&&<><h2 className="oep-headline text-2xl mt-10">Empresas de la cartera</h2>{companies.map(r=><Link className="project-list-row" key={r.key} href={entityLink('titular',r.key)}><span>{r.name}</span><strong>{money(r.investment)}<small>US$ MM</small></strong></Link>)}</>}</div><aside><h2 className="oep-headline text-2xl mt-10">Proyectos recientes</h2>{recent.map(r=><button className="project-list-row" key={r.id} onClick={()=>update({project:r.id})}><span>{r.n}<small>{r.fp} · {r.e}</small></span><strong>{money(r.m)}<small>US$ MM</small></strong></button>)}</aside></div>}<CutoffNote/></>}{filters.project&&<ProjectDetail id={filters.project} close={()=>update({project:null})}/>}</main>;
}
